# Basic
title: Zinuo Li
subtitle: 李 子诺
welcome_message: Welcome to my site. 
description: Java EE | Big data | Machine Learning 
creator: <a href="http://zinuo.me">@zinuoli</a>

url: "http://zinuo.me"

permalink: /:year/:month/:title/

# Format
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit my blog

# Project button
project_button:
    title: Projects
    description: Visit project page

# About button
about_button:
    title: About
    description: About

# Resume button
resume_button:
    title: Resume
    description: click to check

# Navigation buttons in the front page.
# nav:
#     - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
#     # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: arnoldzl
    twitter: Zinuolee
    #gplus: 107108267983477358170
    mail: zli156@hawk.iit.edu
    facebook: arno.lee.56
    linkedin: arnoldzl

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
